### ISSUE TITLE
LCD时钟与TIM冲突

### ISSUE THREAD

**Issue by ly0koS** [ly0koS/EnvControl-Software#16]
LCD配置时钟为168MHz和TIM配置的时钟频率相冲突，需要修改

**Comment by ly0koS** [comment]
修改各中断加自增变量加判断，CO2--0.5s,light--1s,T&RH--1s

**Comment by ysq0908** [comment]
CO2--0.5s   light--0.25s    T&RH--0.25s

**Comment by ysq0908** [comment]
已修改

**Comment by ysq0908** [comment]
RH&T--0.15s  light--0.25s  CO2--0.5s
