### ISSUE TITLE
定标

### ISSUE THREAD

**Issue by ly0koS** [ly0koS/EnvControl-Software#8]
光强：
温度：
湿度：
CO2：

**Comment by ysq0908** [comment]
温度：28°—29°
湿度：
CO2：0.06%
光强：

**Comment by ly0koS** [comment]
湿度：75%
光：200lx

**Comment by ly0koS** [comment]
温度：28°—29°
湿度：75%
光强：200lx
CO2：0.06%
CO2：450ppm----------GOOD
          450-1000ppm----Normal
          1000+ppm-------Poor

**Comment by ly0koS** [comment]
温度：28°-29°
湿度：40-75%
光强：200lx
CO2：0.06%
CO2：450ppm----------GOOD
450-1000ppm----Normal
1000+ppm-------Poor

**Comment by ysq0908** [comment]
温度：18°-29°
湿度：40-75%
光强：200lx
CO2：0.06%
CO2：450ppm----------GOOD
450-1000ppm----Normal
1000+ppm-------Poor
